// src/components/LoadingSpinner.tsx
import React from 'react';
import './LoadingSpinner.css';

const LoadingSpinner: React.FC = () => {
  <div className="spinner">
  <div></div>   
  <div></div>    
  <div></div>    
  <div></div>    
  <style jsx>{`
    .spinner {
      width: 17.6px;
      height: 17.6px;
      animation: spinner-o824ag 1.2s infinite linear;
      position: relative;
    }
    .spinner div {
      position: absolute;
      width: 100%;
      height: 100%;
      background: #9447ff;
      border-radius: 50%;
      animation: spinner-vse6n7 1.5s infinite ease;
    }
    .spinner div:nth-child(1) {
      --rotation: 90;
    }
    .spinner div:nth-child(2) {
      --rotation: 180;
    }
    .spinner div:nth-child(3) {
      --rotation: 270;
    }
    .spinner div:nth-child(4) {
      --rotation: 360;
    }
    @keyframes spinner-vse6n7 {
      0%, 100% {
        transform: rotate(calc(var(--rotation) * 1deg)) translateY(0);
      }
      50% {
        transform: rotate(calc(var(--rotation) * 1deg)) translateY(300%);
      }
    }
    @keyframes spinner-o824ag {
      to {
        transform: rotate(360deg);
      }
    }
  `}</style>
</div>
);
};

export default LoadingSpinner;